# 数据路径配置
paths:
  # 原始数据路径
  origin_data: ''
  
  # 处理后的数据路径
  processed_data: ''
  
  # 输出结果路径
  output_base: ''
  
  # 错误日志路径
  error_log: 'error.txt'

# 文件路径配置
files:
  # 微表情标签文件
  micro_label: 'cas(me)3_part_A_ME_label_JpgIndex_v2.xlsx'
  
  # 宏表情标签文件
  macro_label: 'cas(me)3_part_A_MaE_label_JpgIndex_v2_emotion.xlsx'
  
  # 面部关键点检测模型
  face_landmark_model: 'shape_predictor_68_face_landmarks.dat'

# 文件夹结构
folders:
  # 处理后的数据子目录
  crop_color: 'crop_color'
  crop_depth: 'crop_depth'
  p68: 'p68'
  flow: 'flow'
  txt: 'txt'
  
  # 输出结果子目录
  dataset_seg_part: 'dataset_seg_part'

# 表情类型
expression_types:
  micro: 'micro'
  macro: 'macro'

# 表情标签映射
emotion_labels:
  0: 'anger'
  1: 'happy'
  2: 'disgust'
  3: 'fear'
  4: 'sad'
  5: 'surprise'
  6: 'others'

# 微表情情绪映射
micro_emotion_map:
  'anger': 0
  'happy': 1
  'disgust': 2
  'fear': 3
  'sad': 4
  'surprise': 5
  'others': 6

# 宏表情情绪映射（包含别名处理）
macro_emotion_map:
  'anger': 0
  'happy': 1
  'happiness': 1  # 别名映射到happy
  'disgust': 2
  'fear': 3
  'sad': 4
  'sadness': 4    # 别名映射到sad
  'surprise': 5
  'others': 6

# 点云处理参数
point_cloud:
  # 相机参数
  focal_length: 1324.65
  scaling_factor: 1000
  
  # 每个区域的点数
  num_points: 1024
  
  # 点云大小阈值
  min_point_cloud_size: 15000

# 文件格式
formats:
  # 图像文件格式
  color_image: '.jpg'
  depth_image: '.png'
  
  # 数据文件格式
  landmarks: '.npy'
  flow_image: '.jpg'
  flow_data: '.mat'
  flow_npy: '.npy'
  point_cloud: '.txt' 